---
abstract: 'Dispatch actions based on HTTP Accept Header'
author:
  - 'John Napiorkowski L<email:jjnapiork@cpan.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller::ActionRole: 0
  Catalyst::Test: 0
  ExtUtils::MakeMaker: 6.42
  HTTP::Request::Common: 0
  Moose: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Catalyst::ActionRole::MatchRequestAccepts
name: Catalyst-ActionRole-MatchRequestAccepts
no_index:
  directory:
    - inc
    - t
requires:
  HTTP::Headers::Util: 0
  Moose: 0
  Perl6::Junction: 0
  namespace::autoclean: 0
  perl: 5.8.8
resources:
  homepage: http://search.cpan.org/dist/Catalyst-ActionRole-MatchRequestAccepts/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/Catalyst-ActionRole-MatchRequestAccepts.git
version: 0.03
